import CashierTemplate from "@/components/cashierTemplate"
import CahsierList from "../../cashierList"

export const metadata = {
    title: 'Order | Ordering System',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <CashierTemplate title="Order" id="order" menuList={CahsierList}>
            {children}
        </CashierTemplate>
    )
}

export default RootLayout