import ManagerTemplate from "@/components/cashierTemplate"
import CashierList from "@/app/cashierList"

export const metadata = {
   title: 'Menu | Ordering System',
   description: 'Generated by create next app',
}

type PropsLayout = {
   children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
   return (
      <ManagerTemplate title="Menu" id="Menu" menuList={CashierList}>
         {children}
      </ManagerTemplate>
   )
}

export default RootLayout

